name: covid
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - requests
  - ipython
  - astropy
  - george
  - numpy 
  - scipy
  - matplotlib
  - tqdm
  - statsmodels
  - pip:
    - -r requirements.txt
